#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="${BUILD_DIR:-build}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
GENERATOR="${GENERATOR:-Ninja}"
WEBRTC="${LOCALCALL_WITH_WEBRTC:-ON}"
OPENCV="${LOCALCALL_WITH_OPENCV:-AUTO}"
MULTIMEDIA="${LOCALCALL_WITH_MULTIMEDIA:-ON}"

cmake -S . -B "$BUILD_DIR" -G "$GENERATOR" \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DLOCALCALL_WITH_WEBRTC="$WEBRTC" \
  -DLOCALCALL_WITH_OPENCV="$OPENCV" \
  -DLOCALCALL_WITH_MULTIMEDIA="$MULTIMEDIA"

cmake --build "$BUILD_DIR" --parallel
printf '\nBuilt: %s/LocalCall\n' "$BUILD_DIR"
